Update acp_rule.py
amotolani/fmc_collections pull request #11
Opened 2022-06-21 12:51 UTC by outlawww

added option to add rules if ACP is empty, therefore "InsertAfter" or "InsertBefore" can't be set.
Corrected the log options with correct variable names expected by "AccessRules" class.

2022-06-22 10:00 UTC, amotolani requested changes

2022-06-22 10:12 UTC, amotolani commented
Just did some testing on this and it does work as it should but there are some other implications i noticed. Wondering if you did notice same while testing.

Testing with FMC API Version 6.3. 

When enabling logging (either `logBegin` or `logEnd` ) it seems the FMC API always expects that you set `sendEventsToFMC` to `true` . 

This is not the case while using the Management Console. In the Console you can set the logging destination to only `syslog` and that works fine. 

Here is a sample request body to the FMC API 

`
{
   "id":"005056BF-4E01-0ed3-0000-000268435459",
   "name":"Demo-Rule1903",
   "type":"AccessRule",
   "action":"ALLOW",
   "enabled":true,
   "sendEventsToFMC":false,
   "logBegin":true,
   "logEnd":false,
   "sourceNetworks":{
      "objects":[
         
      ],
      "literals":[
         {
            "type":"host",
            "value":"10.1.1.22"
         },
         {
            "type":"host",
            "value":"10.2.2.11"
         }
      ]
   },
   "destinationNetworks":{
      "objects":[
         
      ],
      "literals":[
         {
            "type":"host",
            "value":"10.4.4.88"
         }
      ]
   },
   "sourcePorts":{
      "objects":[
         {
            "name":"HTTPS",
            "id":"1834bd00-38bb-11e2-86aa-62f0c593a59a",
            "type":"ProtocolPortObject"
         }
      ]
   },
   "destinationPorts":{
      "objects":[
         {
            "name":"LDAP",
            "id":"1834d01a-38bb-11e2-86aa-62f0c593a59a",
            "type":"ProtocolPortObject"
         }
      ]
   },
   "enableSyslog":true,
   "newComments":[
      
   ],
   "commentHistoryList":[
      
   ]
}
`
and here is the API response 

`
{
  "error": {
    "category": "FRAMEWORK",
    "messages": [
      {
        "description": "Provide at least one destination for Connection Events to be logged to."
      }
    ],
    "severity": "ERROR"
  }
}
`
The implication of this is that the are errors when a user tries to do this same thing with the collection. Of course this is a an issue with the FMC API itself but it needs to be thought of here.

2022-06-23 14:27 UTC, outlawww commented on amotolani/cisco_fmc/plugins/modules/acp_rule.py
> +        elif _create_obj:
I agree. But if we set the variables in ansible playbook to "null", will it still work? I' mean like:
```
      insert_after: null
      insert_before: null
```

2022-06-23 14:34 UTC, outlawww commented
It seems they fixed the API in later releases, I just tested with FMC 6.6.1 and it works normal 
![image](https://user-images.githubusercontent.com/30106075/175324839-52e23a86-f919-4782-84f3-12913b4fafb7.png)

2022-06-24 12:36 UTC, amotolani commented on amotolani/cisco_fmc/plugins/modules/acp_rule.py
> +        elif _create_obj:
yes

2022-06-24 12:38 UTC, amotolani commented on amotolani/cisco_fmc/plugins/modules/acp_rule.py
> +        elif _create_obj:
Once we have this merged. I will push the new version to [galaxy](https://galaxy.ansible.com)

Thanks for contributing !

2022-08-12 09:26 UTC, amotolani commented on amotolani/cisco_fmc/plugins/modules/acp_rule.py
> +        elif _create_obj:
```suggestion
        elif _create_obj and insert_before is None and insert_after is None:
```

2022-08-12 09:29 UTC, amotolani commented on amotolani/cisco_fmc/plugins/modules/acp_rule.py
> +        elif _create_obj:
I think it maybe a bit annoying that you have to pass `null` values for parameters you don't want to set anyway.

2022-08-12 09:36 UTC, amotolani approved these changes

2022-08-12 09:37 UTC, merged